service: souvenir-lamda

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-2

functions:
  soveniors:
    handler: src/handler.healthCheck
#     events:
#       - http:
#           method: get
#           path: /health
